### ISSUE TITLE
그냥 꺼집니다

### ISSUE THREAD

**Issue by Psychopath7** [qn1213/OHLI24-DL#1]
폴더 2개 추가하고 SMB파일 안에 Downloader_a0.2.1 파일 넣어서 ohli24Downloader.exe 실행하고 저 링크 넣었는데 아래처럼 뜨고 자동으로 프로그램이 꺼집니다. 혹시 다운됐나싶어서 testani 파일들어가서 save 파일이나 working 파일봐도 아무것도 없습니다.

[Info] : https://a19.ohli24.com/e/%EC%9E%A5%EC%86%A1%EC%9D%98%20%ED%94%84%EB%A6%AC%EB%A0%8C%201%ED%99%94
START Worker
[Broker Done]
[Done]
\

**Comment by qn1213** [comment]
m3u 파일을 받아오는 구조가 바껴서 분석 끝나는데로 다시 업데이트 하겠습니다.
제보 감사합니다.

**Comment by qn1213** [comment]
https://github.com/qn1213/OHLI24-DL/releases/tag/alpha_0.2.2
업데이트 했습니다. 새로 받아주세요.

**Comment by Pindang2** [comment]
20241021 기준 동일한 오류 발생합니다.
https://a24.ohli24.com/e/%EB%B4%87%EC%B9%98%20%EB%8D%94%20%EB%A1%9D!%201%ED%99%94

**Comment by Psychopath7** [comment]
> 20241021 기준 동일한 오류 발생합니다.
https://a24.ohli24.com/e/%EB%B4%87%EC%B9%98%20%EB%8D%94%20%EB%A1%9D!%201%ED%99%94
> [Oct 21, 2024](#issuecomment-2425178063)

rickmiron의 도움을 받아 hitomi downloader에서 사용이 가능한 ohli24 스크립트 파일을 만들었습니다!
https://github.com/Psychopath7/ohli24_script/blob/main/ohli24_downloader.py

'옵션'-'설정'-'플러그인'에 스크립트 파일 추가 후 '작업'-'저장' 하시면 나중에 따로 스크립트 또 불러올 필요 없이 바로 다운로드 가능합니다!
https://ohli24.com/c/Re:%20%EC%A0%9C%EB%A1%9C%EB%B6%80%ED%84%B0%20%EC%8B%9C%EC%9E%91%ED%95%98%EB%8A%94%20%EC%9D%B4%EC%84%B8%EA%B3%84%20%EC%83%9D%ED%99%9C%203%EA%B8%B0 같은 목록URL도 한번에 다운로드 가능합니다!
